require:
  - rubocop-thread_safety
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/schema.rb'
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 120
Layout/MultilineOperationIndentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Rails:
  Enabled: true
