---
styleguide: kf8a/linters
engines:
  reek:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
    enabled: true
    channel: latest
  scss-lint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    config:
      languages:
      - ruby
    enabled: true
  remark-lint:
    enabled: true
  bundler-audit:
    enabled: true
exclude_paths:
- bin
- config
- db
- features
- public
- script
- spec
- test
- vendor
- doc
- app/assets/javascripts/d3.js
- app/assets/javascripts/protovis-d3.2.js
- app/assets/javascripts/jquery.jstree.js
- app/assets/javascripts/jquery.comboselect.js
- app/assets/javascripts/themes
- app/assets/javascripts/application.js
- app/assets/javascripts/jquery.truncator.js
- app/assets/javascripts/jquery.selso.js
- app/assets/javascripts/jquery.quickTree.js
