--- 
javascripts: 
- base: 
  - rails
  - jquery.truncator
  - jquery.quickTree
  - application

stylesheets: 
- base: 
  - formtastic
  - formtastic_changes
  - scaffold
  - branding
  - navigation
  - data
  - kbs
  - glbrc
  - lter_supplemental
