--- 
javascripts: 
- base: 
  - prototype
  - effects
  - controls
  - jquery.truncator
  - jquery.quickTree
  - application
  - textile-editor
  - textile-editor-config

stylesheets: 
- base: 
  - formtastic
  - formtastic_changes
  - branding
  - data
  - kbs
  - glbrc
  - navigation
  - scaffold
  - textile-editor
  - jquery.ui.core
  - jquery.ui.resizable
  - jquery.ui.accordion
  - jquery.ui.autocomplete
  - jquery.ui.button
  - jquery.ui.dialog
  - jquery.ui.slider
  - jquery.ui.tabs
  - jquery.ui.datepicker
  - jquery.ui.progressbar

