--- 
javascripts: 
- base: 
  - prototype
  - effects
  - controls
  - jquery.truncator
  - jquery.quickTree
  - application
  - textile-editor
  - textile-editor-config

stylesheets: 
- base: 
  - branding
  - data
  - kbs
  - navigation
  - scaffold
  - textile-editor
  - themes/base/jquery.ui.base

