--- 
javascripts: 
- base: 
  - prototype
  - effects
  - controls
  - application
  - textile-editor
  - textile-editor-config
stylesheets: 
- base: 
  - branding
  - data
  - kbs
  - navigation
  - scaffold
  - textile-editor
