
package_path: 'packages'
javascript_compressor: closure

javascripts: 
  base1: 
  - public/javascripts/rails.js
  - public/javascripts/less.js
  - public/javascripts/jquery.tokeninput.js
  - public/javascripts/protovis-d3.2.js
  - public/javascripts/proto-graphs.js
  - public/javascripts/jquery.truncator.js
  - public/javascripts/jquery.quickTree.js
  - public/javascripts/jquery.comboselect.js
  - public/javascripts/jquery.selso.js
  - public/javascripts/jquery.combo-select-init.js
  # - public/javascripts/drop_and_drag.js
  - public/javascripts/application.js

stylesheets: 
  base: 
  - public/stylesheets/formtastic.css
  - public/stylesheets/formtastic_changes.css
  - public/stylesheets/token-input.css
  - public/stylesheets/token-input-mac.css
  - public/stylesheets/jquery.comboselect.css
  # - public/stylesheets/drop_and_drag.css
  glbrc:
  - public/stylesheets/branding.css
  - public/stylesheets/kbs.css
  - public/stylesheets/i7-and-down.css
  - public/stylesheets/scaffold.css
  - public/stylesheets/navigation.css
 
