source :gemcutter
gem "rails", "~> 2.3.10"
gem "fastercsv" unless RUBY_VERSION > "1.9"
gem "acts-as-taggable-on"
gem "paperclip"
gem 'nokogiri'
gem 'RedCloth'
gem 'thinking-sphinx', :lib     => 'thinking_sphinx'
gem 'liquid'
gem "clearance"
gem 'formtastic'
gem 'zipruby'
gem 'less'
gem 'subdomain-fu'


group :development do
  # bundler requires these gems in development
  # gem "rails-footnotes"
end

group :test do
  if RUBY_VERSION > "1.9"
    gem 'simplecov'
    gem 'simplecov-html'
  end
  gem "shoulda"
  gem "factory_girl" 

  gem "rspec"
  gem "rspec-rails"
end

group :cucumber do
  gem "shoulda"
  gem "factory_girl"

  gem 'cucumber-rails',   :lib => false, :version => '>=0.3.2' unless File.directory?(File.join(Rails.root, 'vendor/plugins/cucumber-rails'))
  gem 'database_cleaner', :lib => false, :version => '>=0.5.0' unless File.directory?(File.join(Rails.root, 'vendor/plugins/database_cleaner'))
  gem 'capybara',         :lib => false, :version => '>=0.3.5' unless File.directory?(File.join(Rails.root, 'vendor/plugins/capybara'))
end