development:
  min_infix_len: 3
test:
  min_infix_len: 3
production:
  min_infix_len: 4
  pid_file: /var/u/apps/metadata/shared/pids/searchd.pid
  searchd_file_path: /var/u/apps/metadata/shared/db/sphinx
  bin_path: /usr/bin/
