development:
  min_infix_len: 1
test:
  min_infix_len: 1
production:
  min_infix_len: 1
  pid_file: /var/u/apps/metadata/shared/pids/searchd.pid
  searchd_file_path: /var/u/apps/metadata/shared/db/sphinx
  bin_path: /usr/bin/
