development:
  mysql41: 9312
  min_infix_len: 3
test:
  min_infix_len: 3
production:
  enable_star: true
  min_infix_len: 3
  pid_file: /var/u/apps/metadata/shared/pids/searchd.pid
  searchd_file_path: /var/u/apps/metadata/shared/db/sphinx
  bin_path: /usr/bin/
